### PR TITLE
Manual controls

### PR DESCRIPTION
**Pull request by guimeira**
This pull request provides access to manual controls for the camera: ISO, white balance and exposure compensation.

Exposure compensation maps to [setExposureCompensation](https://developer.android.com/reference/android/hardware/Camera.Parameters.html#setExposureCompensation(int)) on Android and [setExposureTargetBias](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1624637-setexposuretargetbias?language=objc) on iOS. On iOS it is also possible to set the exposure duration using [setExposureModeCustomWithDuration](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1624646-setexposuremodecustomwithduratio?language=objc).

White balance on Android can be set to any of the presets defined in the [API](https://developer.android.com/reference/android/hardware/Camera.Parameters.html#WHITE_BALANCE_AUTO) and I tried to reproduce those presets on iOS using color temperatures taken from some white balance table I found online. On iOS it is also possible to set the white balance directly using color temperature and tint. Those values are converted do device-specific gains using [deviceWhiteBalanceGainsForTemperatureAndTintValues](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1624628-devicewhitebalancegainsfortemper?language=objc).

ISO support on Android is somewhat hacky, since the API does not support it. So I search Camera.Parameters for some known ISO attributes and try to use them. I guess it's the best we can do without moving to the Camera2 API. On iOS it maps to [setExposureModeCustomWithDuration](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1624646-setexposuremodecustomwithduratio?language=objc).

If the maintainers are interested in merging this pull request, I'll be happy to make any changes you consider necessary.

### CODE REVIEW

**Comment by timomeara** [comment]
@lwansbrough please merge this pr !!

**Comment by jgcmarins** [comment]
@timomeara , talk to @ptomasroos

**Comment by lfiorini** [comment]
I'm very interested in this PR. I can provide funds for it.

**Comment by THPubs** [comment]
I'm also interested in this PR. Can someone please review and merge it soon?

**Comment by jgcmarins** [comment]
@jgfidelis and @sibelius this PR makes sense after the changes we've done?

**Comment by sibelius** [comment]
We could add this to old implementation, and see if it makes sense for the new implementation as well

**Comment by jgfidelis** [comment]
@guimeira if you can solve the conflicts, please do it and we can merge it

**Comment by zyfccc** [comment]
May I ask is this branch merged?

**Comment by sibelius** [comment]
First we need to fix the conflicts

Feel free to send another pr that fix the conflicts

**Comment by fxcosta** [comment]
Any news? how can i see whats conflicts exists? I'm also interested in this PR and maybe can i help

**Comment by jgcmarins** [comment]
@guimeira could you help us rebasing?

**Comment by guimeira** [comment]
@jgcmarins Sure! I'm happy to help, but it might take me a few days, since I'm a little busy at the moment.

**Comment by sibelius** [comment]
let's implement this for RNCamera instead of RCTCamera

we gonna accept another PR that brings this to RNCamera

**Pull request closed without merging**
