### PR TITLE
Fix Build

### PR DESCRIPTION
**Pull request by tadeumx1**
Because of issue #2179 I am changing the version of com.facebook.infer.annotation to fix the build

### CODE REVIEW

**Comment by tadeumx1** [comment]
I tried with all versions of this avaiable https://mvnrepository.com/artifact/com.facebook.infer.annotation/infer-annotation but nothing build

**Comment by Strate** [comment]
@tadeumx1 why you change version to `10.0.0`, but https://mvnrepository.com/artifact/com.facebook.infer.annotation/infer-annotation has only 0.* versions?

**Comment by tadeumx1** [comment]
First I changed to this version because of the commentary of @shtengel on issue #2179 but after I realized that the package, doesnt have this version, so I found this list of versions available to this package, and I tried all of them but nothing build

**Comment by shtengel** [comment]
I probably took 0.10.0.0 and forgot the initial :) 
My issue was that it failed to build when gradle has com.facebook.infer.annonations:+
So I checked 0.10.0.0 and then I managed to build. I was changing the build.gradle of react-native-camera

**Comment by shtengel** [comment]
@tadeumx1  i changed it to 0.10.0
`  implementation 'com.facebook.infer.annotation:infer-annotation:0.10.0'`
but maybe there is a deeper issue..

**Comment by tadeumx1** [comment]
Thanks for the help, @shtengel I think that I tried with this version of com.facebook.infer.annotation, but I am going to make a commit with this

**Comment by shtengel** [comment]
Thank you for fixing this issue so fast ! :)

**Comment by sibelius** [comment]
fixed here https://github.com/react-native-community/react-native-camera/pull/2194

tks

**Pull request closed without merging**
