### PR TITLE
Fix issue #249 - capture to camera roll crashes on certain Android de…

### LINKED ISSUE #249: capture to camera roll crashes on certain Android devices
### Steps to reproduce
1. install react-native-camera on a clean samsung device e.g. galaxy tab 4
2. ensure no photos have been taken
3. use react-native-camera to capture picture and store to camera roll
4. app crashes b/c sdcar/DCIM/Camera is missing
### Expected behaviour

image is captured and saved to camera roll
### Actual behaviour

image is captured and crashes when saving to camera roll because DCIM/Camera directly is not found
### Environment
- **Node.js version**: 5.2
- **React Native version**: 0.3.8
- **React Native platform + platform version**: Android KitKat
### react-native-camera

**Version**: npm version or "master"

### PR DESCRIPTION
**Pull request by cdimascio**
Fix #249 - To resolve the crash, this fix creates the missing directory if necessary

### CODE REVIEW

**Comment by rt2zz** [comment]
I realize you did not write the original implemenation, but would it not make sense to leverage the react-native [CameraRollManager](https://github.com/facebook/react-native/blob/9a0539d2c48c528d44ddb53d6ea8343890b0ddaa/ReactAndroid/src/main/java/com/facebook/react/modules/camera/CameraRollManager.java) instead of managing this ourselves?

**Comment by rt2zz** [comment]
Also thank you for PR! if anyone with more android/java experience than myself can review that would be much appreciated.

**Comment by cdimascio** [comment]
Sure thing. Happy to help. I agree with you. It may be best to leverage the CameraRollManager. Until that refactoring is complete this fix should avoid app crashes on most devices. Note that we are using this code in our app and have verified that it works on >15 Android devices at various OS versions.

**Comment by dcworldwide** [comment]
Agree with @cdimascio. We can improve the solution later. @rt2zz good to merge?

**Comment by joewood** [comment]
I think I'm seeing this issue on a device. Any chance you could merge?

**Comment by error-bruno** [comment]
This solution fixes my Nexus 6 device from crashing after taking a picture.

**Comment by charpeni** [comment]
Conflicting files, are you up to fix this?

**Comment by sibelius** [comment]
maybe this should be on react-native camera roll module

**Comment by monolithed** [comment]
This should be actualised with the latest changes

**Pull request closed without merging**
