### PR TITLE
Fix to critical issue "Could not find intellij-core.jar"

### PR DESCRIPTION
**Pull request by alastorohlin**
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-camera'.
> Could not resolve all artifacts for configuration ':react-native-camera:classpath'.
   > Could not find intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.0.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.jar

### CODE REVIEW

**Comment by sibelius** [comment]
tks

**Comment by animaonline** [comment]
Will you push a new version soon? I'm unable to compile the app because of this.

**Comment by pataiadam** [comment]
When will it be published to npm?  Im also unable to compile at this moment 😞

**Comment by sibelius** [comment]
done

**Pull request merged**
