### PR TITLE
Fixing https://github.com/react-native-community/react-native-camera/…

### PR DESCRIPTION
**Pull request by justinkiang**
Fixes Issue #1950

### CODE REVIEW

**Comment by n1ru4l** [comment]
@justinkiang Please convince me that using `dispatch_sync` is the correct approach here. I am not that experienced in objective c but I think dispatch_async would be the better approach?

**Comment by reime005** [comment]
I think `dispatch_sync` makes more sense @n1ru4l, see [this line](https://github.com/react-native-community/react-native-camera/blob/2e680e28d90fded135799fd80520b842b1e6743a/ios/RN/RNCameraUtils.m#L106).

**Comment by n1ru4l** [comment]
@justinkiang @reime005 Can you confirm this solves this issue:

>  I believe this issue is causing barcode recognition to not work when I turn the device landscape in an app that is locked to portrait
(https://github.com/react-native-community/react-native-camera/issues/1950#issuecomment-443014134)

I will try to review this ASAP

**Pull request merged**
