### PR TITLE
Update Camera.js

### PR DESCRIPTION
**Pull request by huynhtansi**
Checking CameraManager is valid before export

### CODE REVIEW

**Comment by jgfidelis** [comment]
rctcamera is deprecated

**Comment by huynhtansi** [comment]
I update for both modules, not only RCTCamera

**Comment by asuri0n** [comment]
nice work ;)

**Comment by n1ru4l** [comment]
This change only affects RCTCamera which is deprecated. Also there is no description why this change should be merged, what issues could be solved?

I am going to close this pull request until a valid explanation is given.

**Pull request closed without merging**
