### PR TITLE
Add cameraId feature to iOS and various bug fixes

### PR DESCRIPTION
**Pull request by cristianoccazinsp**
# Summary

Hello, this PR is mostly to add the cameraId feature from Android to iOS as well in order to be able to select from various cameras. While doing this, I've also found a bunch of other bugs that were also fixed. 

In addition, a second commit tries to fix the zoom issue by adding a new iOS only property: maxZoom. This property can be used to restrict the max zoom calculations.

Please review carefully and let me know of any possible issues. I'm currently using this code on a live app with a good amount of users so I will report back any issues soon.

**There's one "issue" I wasn't able to figure out why it is happening** (and it is not related to this change). The camera view instance seems to be created twice the first time it is used, but only one view is mounted/used. The reason of why RN is creating the view twice is still unknown to me, but the changes to event subscription should improve this in a way that events are not fired if not needed. **I would really appreciate some review from someone else to figure out why this happens, the easy to test is to simply add a log to the RNCamera.m initWithBridge method and observe how it is called twice.**. Fixing this would reduce some additional redundant code that is called and makes the view stay in memory.

Summary:

- Implement getCameraIds and cameraId property to manually select a camera device. This was previously implemented for Android and now added to iOS as well

- Adds a maxZoom property to control extraneous zoom values on iOS. Should help with https://github.com/react-native-community/react-native-camera/issues/1772

- Fix the internal preset being used to properly use a photo and video preset, and check for invalid presets on camera switch.
    - This fixes a bug that would happen after recording. After a recording is complete, the camera preset was set to 4k permanently, and attempting to select any camera that does not support that preset would result in an totally unusable camera. Now, the "Photo" preset is the default which should be the highest quality option for photos, and the previously used "High" preset will be used as video default if no value is provided.
    - This also adds proper support to setting the undocumented "pictureSize" property. Setting this property will change the default photo quality to be that one.

- Minor cleanup to the camera initialization so the same code is not called as many times redundantly (start session / device happening multiple times)
    - The reduced redundant calls to start session and session updates should make the camera startup slightly faster.

- Fix for warnings issued due to misuse of the "isRecording" property. This property was defined as both as a property and a method and was both getting set manually and retrieved with a function. It should now consistently only be retrieved with a function based on the real recording status. Should have no behaivour change, but removes a pesky warning.

- Fix an issue related to the camera getting stuck after a background resume by removing the use of the queue for those two events.

- Fixes a wrong event unsubscription (UIDeviceOrientationDidChangeNotification to UIApplicationDidChangeStatusBarOrientationNotification) from a previous change. Also move event subscriptions to superview changes for consistency and so they are not used/consumed if not needed. After testing, the View of RNCamera is instantiated twice (for some reason I couldn't find) but used only once. RN keeps a reference to the view in memory even after the camera is destroyed, resulting in these events getting fired and handled all the time during the app's lifetime.

## Test Plan

Tested on iPhone 7, iphone X, and iPad mini.

### What's required for testing (prerequisites)?
-

### What are the steps to reproduce (after prerequisites)?
-

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [X] I have tested this on a device and a simulator
- [X] I added the documentation in `README.md`
- [X] I mentioned this change in `CHANGELOG.md`
- [X] I updated the typed files (TS and Flow)
- [X] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by cristianoccazinsp** [comment]
Note that I've also have another update for this to support ultra wide lenses (iOS 13). However, I haven't included it yet because it would need people to use XCode with the SDK for iOS 13 which is quite new. This is because the new ultra wide lense variable is available only on the new SDK:

https://github.com/cristianoccazinsp/react-native-camera/commit/44c7ee8ec0a3568b3932642d18b423a72a6e430e

**Comment by scandinaro** [comment]
@cristianoccazinsp once you get the list of camera IDs for iOS how do you set the camera by id?

**Comment by scandinaro** [comment]
>@cristianoccazinsp once you get the list of camera IDs for iOS how do you set the camera by id?

got it RNCamera prop `cameraId`

**Comment by Tibfib** [comment]
I've been battling a lot of instability issues with react-native-camera (failures to take the picture, crashes) on iOS for the past week and decided to give @cristianoccazinsp's fork a chance and it's much improved. Hoping the maintainers have time to look at this in the near future and get it merged.

**Comment by sibelius** [comment]
is `cameraId`required after this PR?

**Comment by Tibfib** [comment]
> is `cameraId`required after this PR?

No. I haven't made any changes beside swapping out the package.

**Comment by cristianoccazinsp** [comment]
It is not. cameraId set to null/undefined (default) will just do nothing
and use the type prop instead to select the camera as before. It is only
intended for advanced use.

**Pull request merged**
