### PR TITLE
Freeze preview for issue #768

### PR DESCRIPTION
**Pull request by loopingz**
I just freeze the preview to make it more friendly user.

We could split into two promise so the capture return as soon as the shutter worked and then a getCaptureData() to retrieve the info. It would allow developers to change the screen.

### CODE REVIEW

**Comment by wassgha** [comment]
Much needed!

**Comment by loopingz** [comment]
Don't hesitate to try from my repo and give me some feedback

**Comment by wassgha** [comment]
Well you can't really do much with this before #859 is merged. Should also be implemented for iOS.

**Comment by loopingz** [comment]
I just solved the Android issue because on IOS the speed was correct, i dont see the link with #859, i use my fork on my project and works fine

**Comment by cloudsafe** [comment]
@loopingz 
hi,I have tried your codes.
Freeze the preview , this idea is very good,but it's looks like, no cancle freeze.
I think you can finished it.(I'm phper and uier,cannot do it).

**Comment by loopingz** [comment]
Thanks, what do you mean by no cancelation? I m changing screen after the picture, you mean you would like the preview to restart after the promise is returned?

**Comment by cloudsafe** [comment]
yeah,In my case,need take more photos or video.so I think your code can't flexible

**Comment by tonyhb** [comment]
Mmm, I think if we combine this with #859 the change should just be to remove the `startPreview` call on line 535 (https://github.com/lwansbrough/react-native-camera/pull/919/files#diff-c0b5ae039b51e601ab6eba76124ab4c2R535).

[The documentation says](https://developer.android.com/reference/android/hardware/Camera.html#takePicture(android.hardware.Camera.ShutterCallback, android.hardware.Camera.PictureCallback, android.hardware.Camera.PictureCallback, android.hardware.Camera.PictureCallback)) that capturing `is only valid when preview is active` and that the preview will automatically be stopped; we can make it mandatory for users to call `startPreview` after the promise is handled with the photo to retake photos.

**Comment by tonyhb** [comment]
In fact, I just removed `stopPreview` https://github.com/tonyhb/react-native-camera/commit/58740dc13ec9e829d4269897d5cbcbecd5979983 which fixes this issue.

Devs can then call `startPreview()` from #859 to retake photos.

**Comment by sibelius** [comment]
check this https://github.com/lwansbrough/react-native-camera/pull/859

**Comment by sibelius** [comment]
upgrade to RNCamera

**Pull request closed without merging**
