### PR TITLE
serialize setCaptureQuality using sessionQueue

### PR DESCRIPTION
**Pull request by manask88**
fixes https://github.com/lwansbrough/react-native-camera/issues/154 and https://github.com/lwansbrough/react-native-camera/issues/604

### CODE REVIEW

**Comment by thomasobrien99** [comment]
+1

**Comment by flybayer** [comment]
Yes, thank you!!

**Comment by manask88** [comment]
@rt2zz @ptomasroos any news on when we could merge this guy?

**Comment by danlopez** [comment]
+1

**Comment by manask88** [comment]
Hey @lwansbrough @rt2zz @ptomasroos  any chance we can move forward with this guy? please , let me know if there is anything I can help to get this one merged soon.

**Comment by manask88** [comment]
Hey @rt2zz  @lwansbrough @ptomasroos  I  know you guys must be very busy. This PR is very important to us since it's being causing crashes on our app. Is there anything I can do to make things easier and get this merged?

**Comment by flybayer** [comment]
I've been using this fix in production (from a fork), and I can confirm that it fixes this particular crash!

**Comment by jhellman** [comment]
I've forked this as well and it's fixed the crash for us too.

**Comment by ospfranco** [comment]
merged for now, you can use master, but just a word of forewarning, we will be moving to a new library (expo camera library) soon.

**Pull request merged**
