### PR TITLE
Android autoFocusPointOfInterest, Camera & Camera2

### PR DESCRIPTION
**Pull request by Craigtut**
Updates both android's Camera & Camera2 to match the autoFocusPointOfInterest prop supported on iOS.  

Most of the updates are pieced together from various sources as my experience with Android doesn't run incredibly deep. Camera 2's version works but could use a bit more work on it.

Also updates the docs to support changes.

### CODE REVIEW

**Comment by Craigtut** [comment]
@n1ru4l - Wanted to check in and see what your thoughts were around getting this merged into a release. Is there anything else that I need to do on it?

**Comment by n1ru4l** [comment]
@Craigtut sorry for not reviewing this yet. I will try to do it next week!

**Comment by Craigtut** [comment]
@n1ru4l  - Oh no worries, thanks for taking a look! Let me know if there is anything I can do to help

**Comment by n1ru4l** [comment]
@Craigtut Could you please rebase first?

**Comment by Craigtut** [comment]
@n1ru4l - Definitely. Will try and do that in the next couple days

**Comment by Craigtut** [comment]
Alright, rebased and retested (just in my app). All seems to be working.

**Comment by Craigtut** [comment]
@n1ru4l - Alright, rebased and retested (just in my app). All seems to be working.

**Comment by n1ru4l** [comment]
@emgroves You can help by testing. I did not have any time to review this yet.

**Comment by Craigtut** [comment]
@n1ru4l - Just wanted to ping this one again. Would love to have it reviewed and added in.

**Comment by sibelius** [comment]
it looks good to me

maybe we can use more code of https://github.com/CameraKit/camerakit-android

**Comment by Tsiniloiv** [comment]
Giving this a shot, and it doesn't seem to be working quite right for me. Every time it hits the null check in setFocusArea, mCamera is null, so it just doesn't do anything.

**Comment by pedrosimao** [comment]
Is this going to be merged or not?

**Comment by sibelius** [comment]
@pedrosimao can you please test this branch as well?

@Tsiniloiv said is not working, so it does not make sense to merge something that does not work

**Comment by Craigtut** [comment]
@Tsiniloiv - Thanks for testing it. It's definitely working in my project, so maybe I need to setup something fresh and test it again.

mCamera shouldn't be null and if it is then a lot of the rest of the camera functionality shouldn't be working either. Can you double check and see if regular camera functionality is working in your test project? and if the callback onCameraReady is called in your project?

**Comment by sibelius** [comment]
can we have this on example? so more people can easily test?

**Comment by Tsiniloiv** [comment]
@Craigtut The camera seems to work fine, yeah. It can take pictures and record videos, and the autofocus is active. Any specific functionality I should test?

onCameraReady is also called. Is it supposed to be called before or after setFocusArea? 'cause it's happening after, for me.

**Comment by Craigtut** [comment]
@sibelius - Definitely. I'll work on getting it added.

@Tsiniloiv - onCameraReady should definitely be called before setFocusArea gets used. autoFocusPointOfInterest should be used after onCameraReady is called (I should definitely add this to the docs). Is this how you tried to use it?

**Comment by Tsiniloiv** [comment]
@Craigtut I've just got it as a prop, like this:

```
<RNCamera
            ref={ref => {
              this.camera = ref;
            }}
            style={styles.preview}
            zoom={this.state.zoom}
            ratio={this.state.ratio}
            type={this.state.type}
            onCameraReady={() => {this.prepareRatio(); this.checkAvail(); console.log("onCameraReady called!");}}
            autoFocusPointOfInterest={this.state.focusArea}
            permissionDialogTitle={'Permission to use camera'}
            permissionDialogMessage={'We need your permission to use your camera phone'}
          >
```
Is this not the way it's supposed to be used?

**Comment by Craigtut** [comment]
@Tsiniloiv - Ah, I see. Sorry, it's been a while since I actually implemented this. I think if you later were to change autoFocusPointOfInterest after the camera initialized, all would work fine. I've used this for touch to focus, so I'm changing autoFocusPointOfInterest on a touch event.

So, sounds like there is some work I need to do still to make the initial value passes as a prop work correctly. I'll have to dig into this and build out the example to test it more thoroughly.

**Comment by Craigtut** [comment]
Example project has been updated to include a touch to focus example using autoFocusPointOfInterest. You can easily test it out to see autoFocusPointOfInterest in action.

I'm not quite sure how to solve the issue @Tsiniloiv brought up. The initial value that you pass autoFocusPointOfInterest has no effect since native side the actual camera hasn't been initialized yet when RNCamera gets rendered. Maybe someone with more experience could suggest a way to solve this?

Though, as a side note - I'm not sure why you would want to pass anything specific to autoFocusPointOfInterest when the camera first starts up. I believe the AF already defaults to the center of the screen.

**Comment by sibelius** [comment]
@Craigtut can you rebase?

I think we can open an issue to solve @@Tsiniloiv problem later on

**Comment by Craigtut** [comment]
@sibelius - rebased.

@osdnk @n1ru4l - Lets get this merge in.

**Comment by osdnk** [comment]
I'd love! @sibelius

**Comment by osdnk** [comment]
Can we have it in Expo, @brentvatne?

**Comment by brentvatne** [comment]
@osdnk - yeah we should, cc @sjchmiela

**Comment by sjchmiela** [comment]
@bbarthec is working on adding this feature as part of the major rework of `expo-camera` he's been working on recently. You can track the progress here — https://github.com/expo/expo/issues/3612. 🙂

**Pull request merged**
