### PR TITLE
Update build.gradle to support latest Gradle-plugin/wrapper

### PR DESCRIPTION
**Pull request by SimonErm**
Fixes the problem that occurs when an app with the latest gradle-wrapper and plugin tries to include the module.

### CODE REVIEW

**Comment by sibelius** [comment]
did u test it on debug and release versions?

**Comment by SimonErm** [comment]
I recognized that the occuring problem was caused by a gradle-plugin i used and not by this, but yes it works on debug and release

**Comment by punksta** [comment]
`api` won't work on Android Plugin for Gradle 2.x.x . Most of apps are still use version 2. We will have issues like this: https://github.com/react-native-community/react-native-camera/issues/1145

facebook still use version [2.2.2](https://github.com/facebook/react-native/blob/master/build.gradle#L9) in react-native plugin

`compile` keyword is supported by new android plugin (3.x.x). So I don't see reasons to merge it right now.

**Comment by punksta** [comment]
Please reopen pl when plugin version 3.x.x will be supported by most of apps.
thanks

**Pull request closed without merging**
