### PR TITLE
Added onPictureTaken event emitter to RNCamera in Android

### PR DESCRIPTION
**Pull request by SirNeuman**
I created this pull request because i wanted to pause the preview of the camera and add a screen effect to my app when taking a picture. I was not able to achieve this effect without adding this event because:

In the following situation the preview would pause before taking the picture, and therefore would prevent the picture from being taken at all:

```
onSnapButtonPress = () => {
    this.camera.takePictureAsync().then(() => {
        ....
    });
    this.camera.pausePreview();
}
```

And in the following example the pausePreview would trigger too late, and there would be an awkward amount of time where the preview was still moving and not a long enough period of time spent in the paused preview:

```
onSnapButtonPress = () => {
    this.camera.takePictureAsync().then(() => {
        this.camera.pausePreview();
        ....
    });
}
```

Now with this custom event added I can do:

```
onPictureTaken = () => {
    this.camera.pausePreview();
}

render() {
    return(
        <RNCamera
            ref={(cam) => {
	        this.camera = cam;
	    }}
            onPictureTaken={this.onPictureTaken}
        />
    );
}
```

and the effect works much better. I was looking at previous requests for this in the issues and i found something that [this](https://github.com/react-native-community/react-native-camera/issues/1378) request might address as well. I only implemented this in Android because my app is currently only configured to run on android, and i don't have an environment to set this up and test it on IOS, but it was pretty simple to implement in Android, and shouldn't be too hard to implement an IOS version. I could go ahead and give the IOS implementation a shot if that was needed for this request to go through and if the reviewers wanted me to add the IOS functionality in in order to get this request merged.

### CODE REVIEW

**Comment by austin-payne** [comment]
Nice I need this too! I'll try to add it to iOS. It would be great if this can be merged over the weekend

**Comment by n1ru4l** [comment]
@austin-payne Are you still interested in adding the ios counterpart? Please feel free to open a new pull request for that feature

@SirNeuman Could you please add some documentation. Afterwards I will merge this feature into master!

**Comment by SirNeuman** [comment]
@n1ru4l Cool! I just updated the docs

**Comment by n1ru4l** [comment]
@SirNeuman Thank you 🙂

**Pull request merged**
