### PR TITLE
Various iOS Focus Updates

### PR DESCRIPTION
**Pull request by zaubara**
* Callbacks onFocus/onZoom have been "fixed" (they still use the deprecated class, but work now)
* Subject area monitoring now works; this fixes the "stuck focus" behaviour
* Focus Square is now more iOS-like; the focus taps should persist until area monitoring clears it, but has now decent colors and sizes

### CODE REVIEW

**Comment by jordangrant** [comment]
@zaubara You're a god. I applied your commits to my local and I'm so happy, the lack of auto exposure has been killing me. Thank you. Thank you.

**Comment by zaubara** [comment]
Happy to help!

**Comment by sibelius** [comment]
@zaubara could u please rebase?

**Comment by zaubara** [comment]
Due to lfs quotas I wasn't able to push either the rebased master nor a ff'ed-merge since I physically need to push all the changes... ideas?

**Comment by sibelius** [comment]
try to start again from latest master in a new branch

**Comment by zaubara** [comment]
Turns out git-lfs is triggered in the pre-push hook; disabling the hooks made me able to push. Did a quick test and I think it works; having some trouble in RN.53 updating code on the device.

**Pull request merged**
