### PR TITLE
Updating for React Native Windows 0.62

### PR DESCRIPTION
**Pull request by jonthysell**
# Summary

This PR updates the ReactNativeCameraCPP windows implementation for react-native-windows 0.62, and attempts to close the feature parity gap by adding / fixing a variety of basic features.

Build:
* Updated ReactNativeCameraCPP projects to use the new RNW lib props/targets provided in 0.62 for easier upgrades
* Added new ReactNativeCameraCPP solution and readme with instructions for building locally
* Added ReactNativeCameraCPP61 solution and project to maintain 0.61 support

ReactNativeCameraCPP RNCamera component:
* Added properties: defaultVideoQuality, mirrorVideo, autoFocus, whiteBalance, cameraId
* Removed deprecated properties: torchMode
* Expanded Type constant (front/back) to include other Windows types (Unknown, Top, Bottom, Left, Right)

ReactNativeCamperaCPP RNCamera module:
* Cleaned up async error handling:
    * Uncaught exceptions no longer crash the app, instead returning the error via the promise reject as expected
    * Passed in options and promises are now properly captured so as to not get deleted before async operations are completed
* Fixed issue when passed in option values are doubles instead of integers
* Moved all possible processing off of the UI thread
* Fixed device enumeration by id/type to support non-integrated cameras
* Piped out CaptureTarget constants for "target" option (memory, disk, cameraRoll, temp)
* Added BarCodeType constant stubs
* Added FaceDetection constants stubs
* Added VideoCodec constants for "codec" option (H264, HEVC, WMV)
* takePicture:
    * Added options: target, quality, doNotSave, base64, width, mirrorImage, exif, writeExif
    * Added result properties: width, height, base64, exif
    * Fixed issue where EXIF data was being stripped from photos
* record:
    * Added options: target, mute, quality, maxDuration, videoBitrate, codec
    * Added result properties: codec
* stopRecording: Added implementation
* isRecording: Added implementation
* pausePreview: Added implementation
* resumePreview: Added implementation
* getCameraIds: Added implementation

## Test Plan

All of the new code has been tested locally against both RNW 0.61 and RNW 0.62 using a copy of the example app code.

### What's required for testing (prerequisites)?

A RNW development environment. See [Windows System Requirements](https://microsoft.github.io/react-native-windows/docs/rnw-dependencies).

### What are the steps to reproduce (after prerequisites)?

1. Create a base windows test app:
    ```
    npx react-native init TestApp --version ^0.62
    cd TestApp
    npx react-native-windows-init --version ^0.62
    ```
2. Enable webcam and microphone app capabilities as described here: [Add capability declarations to the app manifest](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/simple-camera-preview-access#add-capability-declarations-to-the-app-manifest)
2. Overwrite `TestApp\App.js` with `examples\basic\App.js`.
3. `npx react-native run-windows`

## Compatibility

| OS | Implemented |
| ------- | :---------: |
| Windows | ✅ |

## Checklist

- [x] I have tested this on a device and a simulator

### CODE REVIEW

**Comment by jonthysell** [comment]
There's a lot of changes here and I'm not sure who to ping about reviewing this. @ddalp?

I originally started this PR just to get the windows implementation building against at 0.62 so I could test autolinking (coming to RNW in 0.63, see https://github.com/microsoft/react-native-windows/pull/5044) against a community module.

However, camera was one of the first community modules with windows support, and it looked like it wasn't really up to par with the current Android and iOS implementations. So I decided to fill out as many of the missing APIs as I could.

But now I need to move onto other things. So my questions are:

1. Can/should I update the documentation with more details of what windows supports? Since the docs power your website I didn't want to make any presumptions about editing them. (I did update the installation doc and I guess husky reformatted the whole thing?)
2. There are still a few remaining features I didn't have time to implement, some big, some large. Can I open some issues tracking them on this repo? I might not be able to get to them right away but having them in issues might make it easier to load balance with other interested people on my team.

**Comment by sibelius** [comment]
if you feel this work is better than the current one, and it does not introduce new bugs, we can merge, open new issues and make the fixes in a more incremental way

I don't have a windows machine to test this

**Comment by jonthysell** [comment]
> if you feel this work is better than the current one, and it does not introduce new bugs, we can merge, open new issues and make the fixes in a more incremental way
> 
> I don't have a windows machine to test this

Yes, I would say that this substantially improves the C++ version, not just in implemented features but also in stability - the overall threading / async pattern was incorrect before and caused all manner of crashes and unhandled promises. This should be a solid base for myself/others to focus on remaining feature work.

**Pull request merged**
