### PR TITLE
Create camera index.d.ts

### PR DESCRIPTION
**Pull request by sunny635533**
add this camera d.ts file for typescript

### CODE REVIEW

**Comment by Fconstant** [comment]
This will conflict with the already created types in `types/index.d.ts`

**Comment by sunny635533** [comment]
sorry，i see the type/index.d.ts until now. So i will give up this PR. Thanks.

**Comment by Fconstant** [comment]
Ok, I'm closing this PR for now. Feel free to open a new one when you're ready :+1:

**Comment by sunny635533** [comment]
Thanks !!!!!

**Pull request closed without merging**
