### PR TITLE
Updating README with RN Camera instruction for iOS simulator

### PR DESCRIPTION
**Pull request by andrewchaa**
# Summary

Currently, README only mentions permission settings for Android. Out of the box, RNCamera doesn't work either on iOS simulator, as it requires a key in Info.plist. I've updated README so that beginners like me would be frustrated.

## Test Plan

N/A as it's just README update

### What's required for testing (prerequisites)?

N/A

### What are the steps to reproduce (after prerequisites)?

N/A

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by sibelius** [comment]
can you also this to the docs?

**Comment by andrewchaa** [comment]
@sibelius Sure. will update docs too

**Comment by andrewchaa** [comment]
@sibelius it turned out that installation page already has the information. It was just hidden from README. I've added the link to installation on README, so that people can navigate to installation page easily for more details.

**Comment by sibelius** [comment]
tks

we need a CONTRIBUTING.md to help contributing easier

I was talking about this documentation https://react-native-community.github.io/react-native-camera/

we can merge now, and improve later on

**Pull request merged**
