### PR TITLE
Update GradleUpgradeGuide.md

### PR DESCRIPTION
**Pull request by zyfccc**
fixed documentation

### CODE REVIEW

**Comment by zyfccc** [comment]
Just updated the documentation

**Comment by watadarkstar** [comment]
@zyfccc What version did the gradle upgrade start at? Can we let others know what version in which this library upgraded the gradle version? I use `0.12.0` and just upgraded to `0.13.0` but I want to know when the gradle upgrade take place.

**Comment by jgfidelis** [comment]
@watadarkstar I believe it was version 1.1.0, not sure though

**Comment by watadarkstar** [comment]
Thanks @jgfidelis !

**Pull request merged**
