### PR TITLE
[Android] Expose barcode bounds and source dimension from google vision barcode scanner

### PR DESCRIPTION
**Pull request by shashankkushwah**
The current google vision barcode scanning is only exposing barcode data and type. I added the bounds and source dimensions in the scan event.

Also, implemented barcode scanning in basic example.

### CODE REVIEW

**Comment by sibelius** [comment]
can you update typescript types?

**Comment by n1ru4l** [comment]
@shashankkushwah You added `react-native-gesture-handler`, however I cannot see any usages.

**Comment by shashankkushwah** [comment]
> can you update typescript types?

@sibelius I am quite new to js, can you please explain what do you mean by that?



> @shashankkushwah You added `react-native-gesture-handler`, however I cannot see any usages.
@n1ru4l I added react-navigation for easy navigation on basic example app. react-native-gesture-handle comes as part of it, might be getting used in iOS back swipe.

**Comment by shashankkushwah** [comment]
@sibelius @n1ru4l on another note. 

The sourceWidth and sourceHeight values in onFramePreview doesn't match with the actual CameraView width and height.

`public void onFramePreview(CameraView cameraView, byte[] data, int width, int height, int rotation)`

this is what the scanning result is for the screen below 

device-2019-02-07-093644

scan result

```
{
  "target": 267,
  "barcodes": [
    {
      "bounds": {
        "origin": {
          "y": "698",
          "x": "320"
        },
        "size": {
          "height": "6",
          "width": "656"
        }
      },
      "type": "CONTACT_INFO",
      "data": "8873845100011B37"
    },
    {
      "bounds": {
        "origin": {
          "y": "869",
          "x": "443"
        },
        "size": {
          "height": "41",
          "width": "534"
        }
      },
      "type": "CONTACT_INFO",
      "data": "887384FF00011B37"
    }
  ],
  "sourceRotation": 90,
  "sourceHeight": 1200,
  "sourceWidth": 1600,
  "type": "barcode"
}
```

The cameraview dimension are 1440x1875. am I missing something?

**Comment by sibelius** [comment]
upgrade the types here

https://github.com/react-native-community/react-native-camera/blob/master/types/index.d.ts

**Comment by sibelius** [comment]
it would be better to update example in another pull request

good enough for now

tks

**Pull request merged**
