### PR TITLE
IOS code scan freezing freezing capability

### PR DESCRIPTION
**Pull request by rjblopes**
Changes required to introduce the following camera behaviour while scanning codes on IOS:
1-Subscribe for a single event camera scan
2-Single event with the code read
3-Camera Preview freezing for a while
4-Camera Preview resumes
5-Subscribe again for single event if needed

Usage:

`<Camera ref={(cam) => this.camera = cam } onBarCodeRead={ ()=>null }/>

Note: onBarCodeRead prop is needed to force Camera component to emit events

componentDidMount(){
this.startScanning();
}

componentWillUnmount(){
this.stopScanning();
}

startScanning() {
this.scanObserver = this.camera.addObserver(this._onBarCodeRead.bind(this));
}

stopScanning() {
this.scanObserver && this.scanObserver.remove();
}

_onBarCodeRead(data){
this.camera.freezeCapture();
Vibration.vibrate();
setTimeout(()=>{
this.camera.unfreezeCapture();
this.startScanning();
}, 3000);
}`

### CODE REVIEW

**Comment by HofmannZ** [comment]
This might actually be a good performance improvement, thought can't you get the same effect by unmounting the Camara component once you read a barcode?

**Comment by npomfret** [comment]
@rjblopes are you able to ask someone to test this before the contributors take a look (they don't always have time).  Maybe offer to test someone else's PR in exchange for testing yours.

**Comment by cgray9** [comment]
@npomfret - tested this and it works as advertised. Nice work, @rjblopes!

**Comment by rt2zz** [comment]
@rjblopes thank you for PR! Two thoughts
- api should probably be `freezePreview` rather than capture
- we will need the feature implemented for android to get this into master

**Comment by rjblopes** [comment]
Thanks @npomfret, @rt2zz. We are working already on a solution for android and I agree on api naming suggestion.

**Pull request closed without merging**
