### PR TITLE
Picture orientation from sensor

### PR DESCRIPTION
**Pull request by JulienUsson**
Hello,

The camera take device orientation from sensor and no more from the exif data.
I had orientation problems with an app locked in portrait.

Thanks,
Julien Usson

### CODE REVIEW

**Comment by n1ru4l** [comment]
Hey @JulienUsson thank you for your contribution!

Could you please provide a test plan? Like: `hold phone with example app like this, expect image to be like this`. Before and after your changes. That would help enormously!

**Comment by JulienUsson** [comment]
With an app locked in portrait
```
<activity android:name=".MainActivity"
    android:configChanges="orientation"
    android:screenOrientation="portrait"/>
```

When you take a picture in landscape with `this.camera.takePictureAsync({ fixOrientation: true })`

Before : the saved image was not rotated.

After : the picture is saved with the correct orientation.

**Comment by SimonErm** [comment]
I think this is a workaround. There already is a OrientationChecker(https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/com/google/android/cameraview/DisplayOrientationDetector.java), but i think it's not working correctly and that's causing the CameraApi to set wrong exif data sometimes or rotate the picture wrong.

**Comment by JulienUsson** [comment]
My SensorOrientationChecker.java comes from the RCTCamera code because orientation works well with it.
My PR doesn't work on all device like in RCTCamera after doing some tests with other devices.

**Comment by JulienUsson** [comment]
This new version, use exif data and sensor data and now the picture is correctly oriented in all devices.

**Comment by n1ru4l** [comment]
Does this issue address https://github.com/react-native-community/react-native-camera/pull/1941 ?

**Comment by JulienUsson** [comment]
This PR correct the issue #1725

**Comment by Teal-labs-developer** [comment]
@JulienUsson, just one little concern. I think that changing rotating bitmap after picture is captured takes few seconds to process. So why didn't you use the setRotation method for Camera.Parameters?

**Comment by SimonErm** [comment]
@n1ru4l i still think we should fix DisplayOrientationChecker and add an orientation option like we have on ios

**Comment by n1ru4l** [comment]
@SimonErm I agree with you!

@Teal-labs-developer Do you mean when using the `fixOrientation` option?

**Pull request closed without merging**
