### PR TITLE
Add docusaurus

### PR DESCRIPTION
**Pull request by ronal2do**
# Summary
This first PR is only related to adding the docs to create smaller PRs, we need to create 2 more issues for publication and for updating the notes, and adding the API.md

### CODE REVIEW

**Comment by ronal2do** [comment]
I tried to follow the color theme of the react-native-community

Screenshot 2019-06-01 at 13 03 14

**Comment by MateusAndrade** [comment]
This looks REALLY good. Do You need help on anything?

**Comment by sibelius** [comment]
Awesome work

**Pull request merged**
