### PR TITLE
Added Android support for fov

### PR DESCRIPTION
**Pull request by jibarra**

### CODE REVIEW

**Comment by npomfret** [comment]
Hi - thanks for this PR!

Can you describe what someone needs to do in order to test it?  Specifically:

  * what is the expected change in behaviour
  * what steps should a tester make to activate the change in behaviour?

A good way to get this into master is to offer to test someone else's PR in exchange for testing yours.

**Comment by Klyyssi** [comment]
Any news on merging this?

**Comment by jibarra** [comment]
@Klyyssi Sorry, when I made this pull request I didn't find anybody to test it. Would you like to test it?

This pull request adds fov for Android so in order to test these changes you can get the fov from the camera object in the React Native code. Something like this should work:

`this.camera.getFOV().then((data) => { console.log(data[Camera.constants.Type['back']]); });`

**Comment by Klyyssi** [comment]
@jibarra @npomfret This feature was tested with Samsung Galaxy S6 edge+ (Android 7.0), and the values given by the `getFOV()` function were verified using a ruler.

The `data` object above contains the FOV of frontal and rear camera in degrees, that can be read using `data[Camera.constants.Type['back']]` and `data[Camera.constants.Type['front']`.

As stated in a comment in the code, the `getFOV()` function does not actually return vertical FOV, but only the horizontal FOV.

As the camera flips from landscape mode to portrait mode and the other way around, the values given by the function do not change.

If these are considered as expected behavior, I confirm this feature to be working.

**Comment by jibarra** [comment]
Hey @npomfret, can this be merged now? The iOS side does not take the phone orientation into account when calculating the fov.

**Comment by cappe** [comment]
@jibarra I have a question related to the implementation. I noticed your implementation doesn't return the vertical FOV on Android side:

```
@ReactMethod
public void getFOV(final Promise promise) {
    RCTCamera rctCamera = RCTCamera.getInstance();
    // iOS side gets just the horizontal FoV
    double backHorizontalFov = rctCamera.getHorizontalFOV(RCT_CAMERA_TYPE_BACK);
    double frontHorizontalFov = rctCamera.getHorizontalFOV(RCT_CAMERA_TYPE_FRONT);

    final WritableMap response = new WritableNativeMap();
    response.putDouble("" + RCT_CAMERA_TYPE_BACK, backHorizontalFov);
    response.putDouble("" + RCT_CAMERA_TYPE_FRONT, frontHorizontalFov);

    promise.resolve(response);
}
```
I've understood you cannot get vertical FOV on iOS (as stated in the comment above) but on Android it's possible (https://developer.android.com/reference/android/hardware/Camera.Parameters.html#getVerticalViewAngle()). It seems to be implemented in `RCTCamera.java` as well:

```
public double getVerticalFOV(int type) {
        CameraInfoWrapper cameraInfo = _cameraInfos.get(type);
        if (cameraInfo == null) {
            return 0;
        }
        return cameraInfo.verticalFOV;
    }
```

Is there a reason you are not returning the vertical FOV on Android side?

**Comment by jibarra** [comment]
I chose not to return the vertical FOV on the Android side since it's not fully supported on the iOS side. I added the methods to support vertical FOV in case somebody else wanted to fully implement it in the future.

**Comment by cappe** [comment]
Thought so, I guess it's good to keep consistency there. What I was actually thinking here was that if the horizontal and vertical FOVs should be separated into separate methods. We could then provide both consistency and this feature altogether. I understand this'd force clients to apply two different method calls but I feel like it'd be better choice in terms of maintainability and consumability.

I forked your branch and mocked something over the weekend. I also refined what is returned from the getFOV():

```
@ReactMethod
public void getFOV(final Promise promise) {
    RCTCamera rctCamera = RCTCamera.getInstance();
    // iOS side gets just the horizontal FoV
    final WritableMap response = new WritableNativeMap();

    WritableMap back = new WritableNativeMap();
    back.putDouble("horizontal", rctCamera.getHorizontalFOV(RCT_CAMERA_TYPE_BACK));
    back.putDouble("vertical", rctCamera.getVerticalFOV(RCT_CAMERA_TYPE_BACK));

    WritableMap front = new WritableNativeMap();
    front.putDouble("horizontal", rctCamera.getHorizontalFOV(RCT_CAMERA_TYPE_FRONT));
    front.putDouble("vertical", rctCamera.getVerticalFOV(RCT_CAMERA_TYPE_FRONT));

    response.putMap("back", back);
    response.putMap("front", front);

    promise.resolve(response);
}
```

I felt it's cumbersome to use `data[Camera.constants.Type['back']]` so the method now returns the data in the following format:

```
{
    front: {
        horizontal: 64,
        vertical: 49.099998474121094
    },
    back: {
        horizontal: 64,
        vertical: 53.29999923706055
    }
}
```

Then the data could be read something like `data.front.horizontal`.

I could finish these changes during the next week and ask for a PR but I'd like to hear your comments first.

**Comment by sibelius** [comment]
@cappe this https://github.com/react-native-community/react-native-camera/pull/711#issuecomment-343754394 looks good to me

are you willing to send a pr or improve this one, so we can merge this to master?

you can include both horizontal and vertical FOV, and we can figure it out iOS later on

**Pull request closed without merging**
