### PR TITLE
feat(android): support inverted qrcode

### PR DESCRIPTION
**Pull request by zjkhiyori**
I found the lib could not recognized the QRCode which inverted(generic QRCode is white background and filling with black, the inverted is black background and filling with white)

but iOS System Camera can recognized

### CODE REVIEW

**Comment by zjkhiyori** [comment]
inverted QRCode

generic QRCode

**Comment by zjkhiyori** [comment]
> So many try catches, is there a better way?

Emm... cause of `decodeWithState` design
```
public Result decodeWithState(BinaryBitmap image) throws NotFoundException {
    // Make sure to set up the default state so we don't crash
    if (readers == null) {
      setHints(null);
    }
    return decodeInternal(image);
}
```
I have no idea now, can anyone give some advise

**Comment by sibelius** [comment]
good enough for me

**Pull request merged**
