### PR TITLE
fixed the `source_files` path in podspec

### PR DESCRIPTION
**Pull request by bkvirendra**
The podspec `source_files` regex wasn't in sync with the directory structure of the project. Have updated it to use the source files from the relevant directories.

Also updated the `source` attribute to reflect the current repo url.

### CODE REVIEW

**Comment by bkvirendra** [comment]
@sibelius Yes this resolves the issue with pod installs. Like the one mentioned here -> https://github.com/react-native-community/react-native-camera/issues/1248#issuecomment-366318723

**Comment by sibelius** [comment]
could u close all of them? and ask them to retest

tks for ur help

**Comment by bkvirendra** [comment]
@sibelius No worries, I'll close the open issues & inform the users to retest with the current master.

**Comment by benseitz** [comment]
@sibelius Seems it doesn't solve the issues. The error still remains even if using the current master.

**Comment by n1ru4l** [comment]
@benseitz What exactly is not working? It perfectly works for me

**Pull request merged**
