### PR TITLE
chore(semantic-release): setup semantic-release for automated publishes

### PR DESCRIPTION
**Pull request by n1ru4l**
* add semantic-release
* use commitizen for commit linting

This PR replaces #1891 

The motivation behind switching to semantic-release ist https://github.com/react-native-community/react-native-webview which is also using semantic-release for publishing. IMHO it is beneficial to use the same tooling as other react-native-community packages.

### CODE REVIEW

**Comment by sibelius** [comment]
I can't add people to circleci, only admin of @react-native-community can

maybe @brentvatne can help on this

**Comment by brentvatne** [comment]
@sibelius - I made you an admin

**Comment by sibelius** [comment]
tks, @n1ru4l what is your email?

**Comment by n1ru4l** [comment]
@sibelius laurinquast@googlemail.com

**Comment by sibelius** [comment]
try to follow this project on circleci https://circleci.com/gh/react-native-community/react-native-camera

you should be able to setup there

**Comment by n1ru4l** [comment]
Right, will tackle this on the weekend!

**Pull request merged**
