### PR TITLE
Extend interface with _cameraRef and _cameraHandle

### PR DESCRIPTION
**Pull request by Noitidart**

### CODE REVIEW

**Comment by sibelius** [comment]
why is this needed?

**Comment by Noitidart** [comment]
It's to make the type more accurate for TypeScript. TypeScript complains without it. I was using `this.ref._cameraRef.measure` (`<RNCamera ref={this.ref} />`) to get the measurements of the view to figure out the `autoFocusRegionOfInterest` width/height.

**Comment by Noitidart** [comment]
Wow super fast collaboration! thank you!

**Pull request merged**
