### PR TITLE
fix: exclude android build artifacts

### LINKED ISSUE #2000: Package is overweighted
Hi,

After a npm install of your package, the directory size is 16M, mostly due to android build directory, embedding stuff which should not be commited

You should clean that, it's totally useless and horrible for users :)

```
du node_modules/react-native-camera/android/ -h -d 1
68K	node_modules/react-native-camera/android/gradle
4,2M	node_modules/react-native-camera/android/.gradle
596K	node_modules/react-native-camera/android/src
9,5M	node_modules/react-native-camera/android/build
15M	node_modules/react-native-camera/android/
```

### PR DESCRIPTION
**Pull request by n1ru4l**
Closes #2000

TODO: Test if it breaks build as mentioned in https://github.com/react-native-community/react-native-camera/issues/2000#issuecomment-447328777

### CODE REVIEW

**Comment by sibelius** [comment]
We could also build examples on CircleCI, so we can validate when a change breaks the example

**Comment by n1ru4l** [comment]
Great lets do that

**Comment by n1ru4l** [comment]
@Nabellaleen Could you please test if the following works:

```
yarn add react-native-camera@https://github.com/n1ru4l/react-native-camera.git#fix-exclude-build-artifacts` 
```

Ideally run the following commands before installing + building:

```
# ensure gradle caches are busted
rm -rf $HOME/.gradle/caches/
rm -rf <your-project-root>/android/build
```

**Comment by Nabellaleen** [comment]
@n1ru4l : perfect ;) And it builds without any problems

```
$ du node_modules/react-native-camera/android/ -h -d 1
68K	node_modules/react-native-camera/android/gradle
596K	node_modules/react-native-camera/android/src
684K	node_modules/react-native-camera/android/
```

**Pull request merged**
