### PR TITLE
Android ui thread

### PR DESCRIPTION
**Pull request by cristianoccazinsp**
# Summary

Setup a HandlerThread (background thread) to remove heavy operations from the UI thread. This also removes a few redundant calls to camera/preview start, and adds more error checks. Overall, this results in a faster camera startup time, and faster resume from background.

Update is aimed mostly to Camera1 implementation, but Camera2 will also benefit for the start method being called in a non UI thread. 

Issue and video samples here: https://github.com/react-native-community/react-native-camera/issues/2555

Possible improvements: Identify other "slow" methods that might also need to be fired in the background thread. So far, I've only seen start/stop and preview related calls to be slow, but this might be different for other devices.

## Test Plan

Local tested on a Pixel 2 (Android 10) and Motorola G5 (Android 8). Field tested for nearly a week on production (Samsung S9, S8, Motorola Z4 and Z3, Pixel 3 XL, Pixel 4, and a few other models) without issues.

However, could use some extra testing on older devices since our app only supports Android 5 and above.

### What's required for testing (prerequisites)?
Real device

### What are the steps to reproduce (after prerequisites)?
-

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [X] I added the documentation in `README.md`
- [X] I mentioned this change in `CHANGELOG.md`
- [X] I updated the typed files (TS and Flow)
- [X] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by cristianoccazinsp** [comment]
Can't tell what failed with the checks :S

**Comment by cristianoccazinsp** [comment]
There's definitely something wrong with the tests...

**Comment by sibelius** [comment]
flaky

**Comment by cristianoccazinsp** [comment]
@sibelius do you know what's failing exactly with the tests? Doesn't seem to be any java related issue. It's also interesting that it went from "good" to "failed" with a commit that literally just removed two unused imports.

**Comment by cristianoccazinsp** [comment]
Been running on Production for almost 2 weeks, not a single camera crash reported yet, has to be a record!

@sibelius  any updates with tests failing? Did I miss something? The project seems to compile just fine.

**Comment by mars-lan** [comment]
Looks like this PR may have introduced a bug where the preview doesn't get loaded properly again in subsequent captures. It showed a forever spinning wheel instead.

**Comment by cristianoccazinsp** [comment]
@mars-lan  can you provide some more details about that? How are you initializing the camera? I haven't seen any issues so far, and our app is made to take a lot of pictures one behind the other.

Where is the spinning wheel coming from as well? I don't think RNCamera renders any spinning wheel except when awaiting for permissions.

**Comment by mars-lan** [comment]
My bad. Turns out that I was using `pauseAfterCapture` and must call `cameraRef.resumePreview()` before using the camera again.

**Pull request merged**
