### PR TITLE
[ios + android] Added "width", "height" and "uri" to captured image when target is "temp"

### PR DESCRIPTION
**Pull request by kesha-antonov**

### CODE REVIEW

**Comment by npomfret** [comment]
Thanks for this PR.

Why only 

> when target is "temp"

?

**Comment by kesha-antonov** [comment]
Hey! @npomfret 

No special purpose. Just I'm using only "temp"

You want it for all?

**Comment by npomfret** [comment]
Sure.  I don't think it make sense to change the return type for one and not the others.  Maybe images should have the same shape too?

**Comment by kesha-antonov** [comment]
I think so.
I'll add this. I think it's not muck work

**Comment by pewh** [comment]
Hello,

Width & height attribute is very important for me. I'm curious why these not merge to repo?

**Comment by spikeisryu** [comment]
Yes, please merge it to repo ASAP.

**Comment by victorbadila** [comment]
Why is this not merged yet? looks clean :/

**Pull request closed without merging**
