### PR TITLE
Add setZoom API method

### PR DESCRIPTION
**Pull request by bluedaniel**
This adds `setZoom` so you can additionally zoom the camera.

Example usage with a slider.

```js
<Camera ref={c => { this.camera = c; }} />

<Slider
  value={1}
  minimumValue={1}
  maximumValue={16}
  onValueChange={value => this.camera.setZoom(value)}
/>
```

### CODE REVIEW

**Comment by sibelius** [comment]
@bluedaniel this looks good

can somebody test this on real devices on ios and on android, so we can merge?

**Comment by bluedaniel** [comment]
@sibelius this is an iOS only PR.

Java isn't my strong suit but I can give it a go.

**Comment by bluedaniel** [comment]
@sibelius I added some Android code for zooming but I don't have a device to test it on :man_shrugging:

Small gist to test:
https://gist.github.com/bluedaniel/436ad3130b07dd12db2d3f3ec7ded115

**Comment by sibelius** [comment]
@bluedaniel I think it looks good

can u rebase?

**Comment by tirrorex** [comment]
What would be great would be to wrap a PanResponder in react-native-camera.
Basically one could set a zoom to false or with a different value (to zoom faster for example) in the props.
This way we could have the same implementation on both ios and android (that is actually what we have in our apps, but with the native camera wrapped by ourselves).
Thoughts?

**Comment by sibelius** [comment]
@tirrorex I think this can be in user land

or in a recipe in this repo

**Pull request merged**
