### PR TITLE
Do not render component when out of permission

### PR DESCRIPTION
**Pull request by iegik**
Relative to https://github.com/lwansbrough/react-native-camera/issues/743

### CODE REVIEW

**Comment by sibelius** [comment]
should we render children or should we render null?

**Comment by iegik** [comment]
@sibelius, as noted in documentation, You can pass your template trougth children. By default it equals null, isn`t it?

**Comment by sibelius** [comment]
I think checking permission should be in user land instead

not in this package

**Comment by ospfranco** [comment]
This should be addressed with #1076 I think we can close it

**Pull request closed without merging**
