### PR TITLE
fix(rn-camera): fix codec backwards compat

### LINKED ISSUE #1550: [AVCaptureMovieFileOutput availableVideoCodecTypes]: unrecognized selector sent to instance
### Which implementation are you using
*RNCamera*

### Steps to reproduce
I'm really not doing anything fancy. The video recording works perfectly fine on Android but it crashes after `stopRecording()` on iOS.
```
        <RNCamera
          autoFocus={RNCamera.Constants.AutoFocus.on}
          captureAudio={true}
          flashMode={RNCamera.Constants.FlashMode.off}
          notAuthorizedView={<View/>}
          onCameraReady={() => this.handleCameraReady()}
          pendingAuthorizationView={<View/>}
          permissionDialogTitle={'Permission to use camera'}
          permissionDialogMessage={'We need your permission to use your camera phone'}
          ratio="16:9"
          ref={cam => this.camera = cam}
          style={styles.preview}
          type={videoFacing === 'back' ? RNCamera.Constants.Type.back : RNCamera.Constants.Type.front }
          // useCamera2Api={true}
        />
```

### Expected behaviour
Finish recording and return the `uri`.

### Actual behaviour
App crashes with the following error:
```
[AVCaptureMovieFileOutput availableVideoCodecTypes]: unrecognized selector sent to instance 0x14fb4e20
2018-05-08 00:19:49.083 Undercover[620:69647] *** Terminating app due to uncaught exception 
'NSInvalidArgumentException', reason: '-[AVCaptureMovieFileOutput availableVideoCodecTypes]: 
unrecognized selector sent to instance 0x14fb4e20'
```

### Environment
- **Node.js version**: 6.11.0
- **React Native version**: 0.54.0
- **React Native platform + platform version**: iOS 9.3.3

### react-native-camera
**Version**: "master"

### PR DESCRIPTION
**Pull request by n1ru4l**
Attempt to fix #1550

Can someone with an iOS 9 device test this?

### CODE REVIEW

**Comment by n1ru4l** [comment]
@benjaminreid Can you please verify that the code is working using this branch?

With

`npm install react-native-camera@https://github.com/react-native-community/react-native-camera.git#n1ru4l-patch-2`

or

`yarn add react-native-camera@https://github.com/react-native-community/react-native-camera.git#n1ru4l-patch-2`

**Comment by benjaminreid** [comment]
@n1ru4l Yep, I’ll get on it now. Bare with me.

**Comment by benjaminreid** [comment]
I’ve not got an iOS 9 device to hand, so @craigcoles is currently setting up a new build with the branch to a device now. Will report back ASAP.

Thanks you both @n1ru4l and @sibelius for getting on this lightning fast 👏

**Comment by benjaminreid** [comment]
@n1ru4l Perfect, working as expected. Great job 👍 

:shipit:

**Pull request merged**
