### PR TITLE
Fixed issue caused by Google Play Services 12.0.0

### PR DESCRIPTION
**Pull request by chanthouNim**
Problem of Google Play Service: https://github.com/facebook/react-native/issues/18479

### CODE REVIEW

**Comment by sibelius** [comment]
this fix should be in userland

```
compile ('com.google.android.gms:play-services-vision:11.+') {
   force: true
}
```

**Comment by anandwahed** [comment]
@chanthouNim and @sibelius it would be better if this could refactored to use `project-wide` gradle configuration similar to a PR in [react-native-maps](https://github.com/react-community/react-native-maps/pull/2047)

**Comment by sibelius** [comment]
can u send a PR to fix this?

**Comment by anandwahed** [comment]
@sibelius should i create a new PR ?

**Comment by chanthouNim** [comment]
So I will close this pull request, thank @sibelius and @anandwahed

**Comment by Medicean** [comment]
the property `force` should replace `:` with `=` or ` `,  otherwise it will not have the desired effect. 

```
compile ('com.google.android.gms:play-services-vision:11.+') {
   force true
}
```

**Pull request closed without merging**
