### PR TITLE
Update Camera1.java

### PR DESCRIPTION
**Pull request by marekchen**
fix java.lang.RuntimeException: Camera is being used after Camera.release()

### CODE REVIEW

**Comment by n1ru4l** [comment]
@marekchen First of all thank you for your contribution!

Before merging could you please explain how to reproduce the `fix java.lang.RuntimeException: Camera is being used after Camera.release()` crash and provide a test plan for this fix?

**Comment by n1ru4l** [comment]
@SimonErm What is your opinion on these changes?

**Comment by SimonErm** [comment]
@n1ru4l  I am not sure which of these functions throws the exception and your right, just catching without handle it is not the way we should do. I think if we know how to reproduces this, we can fix the root problem.

**Comment by n1ru4l** [comment]
Closing this since it is not the correct solution. Please feel free to open a new pull request that addresses this issue correctly.

**Pull request closed without merging**
