### PR TITLE
[WIP] Prevent camera flickering when starting a recording

### LINKED ISSUE #1249: Black flashing screen when recording video (also saved in the recording)
### Which implementation are you using

*RNCamera*

### Steps to reproduce

1. Mount a video component with autoFocus on
2. Use the reference prop to start recording when pressing the screen

### Expected behaviour
The video start recording without the black going screen for a few milliseconds. Also the video should be saved without black frames at the beginning

### Actual behaviour
The screen turns black for a few milliseconds. The few milliseconds of dark frames are also present in the recording. I think this is related to autoFocus.

### Environment
- **Node.js version**: v8.9.4
- **React Native version**: v0.52.2
- **React Native platform + platform version**: iOS 10

### react-native-camera
**Version**: v1.0.1

### PR DESCRIPTION
**Pull request by delta98**
fixes #1249

### CODE REVIEW

**Comment by n1ru4l** [comment]
@delta98 The changes somewhow prevent the children of `RNCamera` to be rendered

**Comment by delta98** [comment]
> @delta98 The changes somewhow prevent the children of RNCamera to be rendered

Was related to using the old children API and fixed by using the FaaC API.

@n1ru4l I also thought the same, but noticed a bug in the FaCC implementation which wasn't gracefully falling back to rendering children on the old API, there's a bugfix which has just been accepted to resolve this. Will tidy up Face Detection now.

**Comment by watadarkstar** [comment]
@delta98 @n1ru4l I get a crash when I use this branch (did you run into this?):

on this line:
```
[self.movieFileOutput startRecordingToOutputFileURL:outputURL recordingDelegate:self];
```

And get this warning:
```
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.
(lldb) 
```

my js code:
```
startRecording = () => {
    const options = {
      quality: RNCamera.Constants.VideoQuality["480p"],
      mute: true,
      maxDuration: 60 * 3
    };
    if (this.camera) {
      this.camera
        .recordAsync(options)
        .then(data => {
          this.props.upload(data.uri);
          this.navigateToChat();
        })
        .catch(err => console.error(err));
      this.setState({
        isRecording: true
      });
    }
  };
```

**Comment by watadarkstar** [comment]
Thanks @n1ru4l for the quick response! I didn't do a `pod install` so going to try that first before I try that hash 😄

**Comment by watadarkstar** [comment]
Yup @n1ru4l was right that hash seems to work wonders! `react-navigation@https://github.com/delta98/react-native-camera.git#3e9a4fe16935ff14514fd6c311a5505eb4567edc`

**Comment by watadarkstar** [comment]
@n1ru4l Can you post a snippet of your custom compression code? My plan is to un-comment out the quality stuff that  @delta98 commented out and hope I can get the best of both worlds (flicker removed + the quality option being set) like so: https://github.com/watadarkstar/react-native-camera/commit/61e852ee9489b81f046209a143dd46c98bd987fa

**Comment by n1ru4l** [comment]
Or maybe quality might be something that should be adressed in user land

**Comment by watadarkstar** [comment]
@n1ru4l Can you show an example of how you did compression? What libraries did you use?

**Comment by watadarkstar** [comment]
@n1ru4l thanks 😄 ! Any plans to open source that module?

**Comment by jgfidelis** [comment]
What is the status of this? Still a WIP?

**Comment by n1ru4l** [comment]
@jgfidelis Some features like faceDetection and setting the quality is disabled. It seems that using the options of `recordAsync` results in flickering, since those are set just before the recording starts. Like @watadarkstar said, allowing to set them on the component as "initial properties" will prevent any flickers. If you are okay with this I will try to clean up the PR and add those new properties.

**Comment by jgfidelis** [comment]
@n1ru4l if you can keep the bug fix while not disabling any current feature, feel free to finish this pr, looks really useful.

**Comment by n1ru4l** [comment]
@jgfidelis I think that might be doable, but lets try to fix #1613 first 😅

**Comment by delta98** [comment]
Sorry for being silent on this. There was discussion elsewhere on separating the vision APIs from the capture session.

I wasn't able to dedicate anytime to creating an example and updating to allow for a composition of this component with a HoC for the vision api et al `withVisionDetectionProvider`.

Quality issues are more about the position of the code, as mentioned they should be a prop and passed in during init of the session and not during/prior to capture.

**Comment by leshaivanovsky** [comment]
Dear friends! are there any updates on that? Having the very same flickering problem – and the patching doesn't seem to help much because i'm having a newer version of master

**Comment by robyweb** [comment]
Hi, I tried to apply the patch, but then I ran into another known issue where it complained about not being able to write to storage. I have seen that error when I try to record in 1080p on an iPhone SE. Not specifying the quality also doesn't work. 

Any idea when the flickering issue will be merged?

**Comment by n1ru4l** [comment]
@leshaivanovsky @robyweb for now you will have to adjust the patch for your branch. I have no eta for sending a "clean" PR that addresses this issue.

**Comment by heyman333** [comment]
I think this fix should be merged ASAP

**Comment by reime005** [comment]
flickering is solved in #1857 but needs review

**Comment by n1ru4l** [comment]
Closed in favor of #1886

**Pull request closed without merging**
