### PR TITLE
Seblau/fix postinstall pbxproj

### PR DESCRIPTION
**Pull request by seblau**

### CODE REVIEW

**Comment by n1ru4l** [comment]
@seblau Could you please explain this fix? Which issue is solved by it?

**Comment by sibelius** [comment]
this is a workaround to fix projects that uses RNCamera without GMV

check this https://github.com/react-native-community/react-native-camera/blob/b2899adbc1a9c78be74eb4ba858b18dc7335bb1f/README.md#no-face-detection-steps

**Comment by n1ru4l** [comment]
@sibelius You will have to use angular style merge/squash commits in order to trigger releases.

Also GMV is currently broken (at least rncamera-example instacrashes upon launch).

**Comment by sibelius** [comment]
can I do this merge from github interface?

**Comment by n1ru4l** [comment]
@sibelius https://twitter.com/kentcdodds/status/928354431464124416

**Pull request merged**
