### PR TITLE
 Do not rely in to jcenter but google

### LINKED ISSUE #1872: Could not find intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.0.1).
When looking into the URL given it gives Resource not found error. The Jar File might have been removed. 

Steps to reproduce
1. React native init NewCameraProject
2. npm install react-native-camera --save
3. react-native link
4. react-native run-android

On executing step 4, it starts resolving the dependencies for ReactNative Camera: This error is shown in the Terminal:

* What went wrong:
A problem occurred configuring project ':react-native-camera'.
> Could not resolve all files for configuration ':react-native-camera:classpath'.
   > Could not find intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.0.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

### PR DESCRIPTION
**Pull request by sospedra**
Fixes #1872

### CODE REVIEW

**Comment by jdnichollsc** [comment]
+1

**Comment by sospedra** [comment]
Hey @sibelius sorry to bother again ;)
I saw you bumped the source code version to 1.3.1 but it's not published in the `npm` registry. Any luck this is gonna happen soon?

**Comment by jdnichollsc** [comment]
@sospedra 👍

**Comment by sibelius** [comment]
https://www.npmjs.com/package/react-native-camera

**Comment by sospedra** [comment]
Aaaah! Reliable people in the open source world

image

**Pull request merged**
