### PR TITLE
fix(android): prevent shutting down camera when re-mounting children

### PR DESCRIPTION
**Pull request by thymikee**
Fixes https://github.com/react-native-community/react-native-camera/issues/1311

There's a bug where re-mounting children without transparent background shuts down the camera on Android (adb on LG G2 shows that `stopPreview` from `QCamera2HWI` gets called, but I couldn't set up debugging to see what's calling it, help appreciated).

By accident I've found a workaround, which involves wrapping children in a transparent view (not sure why `backgroundColor: 'transparent'` plays role here but it does).

As a manual test I've added a previously buggy behavior to example app – pressing zoom in / zoom out will mount/unmount a `Text` node which is a direct child of `RNCamera`.

### CODE REVIEW

**Comment by n1ru4l** [comment]
I think we should fix the root cause of this issue instead of some temporary hack

**Comment by sibelius** [comment]
Does this happen on Expo câmera module as well?

I think we can use this hacky for now

**Comment by sibelius** [comment]
this is the same code of expo camera https://github.com/expo/expo/blob/eafa96e0d6/packages/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.java#L162

**Comment by sibelius** [comment]
I think we can try to solve this using react native lifecycles

https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/LifecycleEventListener.java#L27

onHostResume
onHostPause
onHostDestroy

my guess is that onPause or onResume is not being called properly by react-native

**Comment by n1ru4l** [comment]
by adding this code to `onViewAdded` the issue is also "solved". Anyway why is the view removed an readded? When you start zooming the first time this behaviour occures. 0 -> 0.1. However on further renders this issue is not present anymore.

```java
   if (hasCameraPermissions()) {
      start();
    }
```

Maybe your solution is the right solution 😕

**Comment by thymikee** [comment]
> Anyway why is the view removed an readded?

Without this method overrriden the React injected UI (children) flash for a split of second and once the component mounts, the camera is put on top. So the solution is to remove and add views with 0 index, because that's supposedly how you can be sure about the view (camera) can be on the very bottom, and React UI is on still on top. Not sure why this happens, maybe because of how the camera screen lays out? 
Here's reference to where it was added: https://github.com/react-native-community/react-native-camera/pull/308

> However on further renders this issue is not present anymore

The camera instance is still present and `isCameraOpen` reports false after the first children re-render (changing zoom from 0 to 0.1)

I'm not experience in Android dev, so it's all new to me and I'm just trying to get my head around it 😅

**Comment by n1ru4l** [comment]
**react-native-linear-gradient** avoids passing in children into the NativeView

https://github.com/react-native-community/react-native-linear-gradient/blob/master/index.android.js#L84

https://github.com/react-native-community/react-native-linear-gradient/blob/master/index.ios.js

Other libraries from `react-native-community` also do not have this issue since they do not allow passing children to the "NativeView" and force users to utilize absolute positioning.

**Comment by thymikee** [comment]
So, maybe we should follow this guidance? Should be possible to remove that hack from 2yrs ago altogether.

**Comment by n1ru4l** [comment]
@thymikee I agree.

I would encourage an implementation like this one: https://github.com/react-native-community/react-native-linear-gradient/blob/master/index.android.js#L84

**Comment by thymikee** [comment]
Gonna work on it over the weekend then! Thanks for helping out

**Comment by n1ru4l** [comment]
@thymikee Thank you for getting this finally fixed 🎉

**Comment by n1ru4l** [comment]
@sibelius Do you know any project that implemented passing children to the native component directly (without the issues we are experiencing)?

**Comment by sibelius** [comment]
we can check on github https://github.com/search?l=Java&q=ViewGroupManager&type=Code

maybe someone in the react native core could help us on this

cc @axe-fb @cpojer

**Comment by thymikee** [comment]
@n1ru4l addressed your feedback, so it still works well and we got rid of a hacky behavior on Android.

**Comment by miracle2k** [comment]
The pull request will fix this, but for completeness sake, I want to point to https://github.com/react-native-community/react-native-camera/issues/1862#issuecomment-433497819 which I believe is the reason why the issue exists when children are added inside the native view.

**Comment by n1ru4l** [comment]
@sibelius Do you want to investigate more or accept this solution? I am fine with this "workaround".

**Comment by sibelius** [comment]
I’m fine with this workaround, we can accept a native solution later on if someone fixes it

**Pull request merged**
