### PR TITLE
feat: barcodefindermask subview for rncamera to show barcode style

### PR DESCRIPTION
**Pull request by shahnawaz**
# BarcodeFinderMask

> A subview for RNCamera to show barcode style layout

<p align="center" >
    
</p>

## Usage

All you need is to `import` `{ BarcodeFinderMask }` from the `react-native-camera` module and then use it inside
`<RNCamera>...</RNCamera>` tag as a child component.

```javascript
'use strict';
import React, { Component } from 'react';
import { RNCamera, BarcodeFinderMask } from 'react-native-camera';

...
    <RNCamera
        ...
    >
        <BarcodeFinderMask />
    </RNCamera>
...
```

Further usage details are added in [BarcodeFinderMask.md](https://github.com/shahnawaz/react-native-camera/blob/feature/BarcodeFinderMask/docs/BarcodeFinderMask.md)

## Why I added this subview in react-native-camera?

Its pretty cool 👍 

(In all seriousness) I have used RNCamera in few projects and well, whenever there is a feature like barcode scanning, clients and customers request to see a styled view instead of a plain screen.

Pros?

- This would make life much more easier for people who are using RNCamera for barcode scanning.
- Easy to use and customize layout.
- Uses RNCamera subview style (children).
- Code is very similar to the style followed in other files.
- A separate doc created for the usage of [BarcodeFinderMask.md](https://github.com/shahnawaz/react-native-camera/blob/feature/BarcodeFinderMask/docs/BarcodeFinderMask.md)

##### Few style examples:

<p align="center" >
    
    
    
</p>

*Note:* Also updated RNCamera.md and added a small section about this subview.

### CODE REVIEW

**Comment by Mohammad-Khalid23** [comment]
@shahnawaz It's great thanks buddy for this, I was this in react-native-camera and It should be add in react-native-camera

**Comment by hcurnor** [comment]
This actually helped me. Thanks!

**Comment by sibelius** [comment]
I’d rather have this in another package, user land

We can link it on docs

**Comment by shahnawaz** [comment]
Thanks sibelius (agreed)

Let me close this PR and send a new one with just a package link in docs

**Comment by brayanL** [comment]
When i try use BarcodeFinderMask, is not available on library, maybe missed this feature?

**Comment by shahnawaz** [comment]
Hi @brayanL  

This feature is packaged into a separate module. Here is the link:

https://github.com/shahnawaz/react-native-barcode-mask

**Pull request closed without merging**
