### PR TITLE
Alex kotov scale focus square

### PR DESCRIPTION
**Pull request by AlexKotov**

### CODE REVIEW

**Comment by ospfranco** [comment]
This is a very big pull request, could you explain a little more what is it that you are trying to achieve?

**Comment by AlexKotov** [comment]
Hi, I develop an app, that uses your lib. And I extend it a little bit.
So, It is my first great extention of someone's lib and I don't understand how I can get all of your updates into my fork.

**Comment by sibelius** [comment]
@AlexKotov can you split this PR in multiple smallers ones?

so we can easily review and merge it

**Comment by AlexKotov** [comment]
I'll try!

**Pull request closed without merging**
