### PR TITLE
Fix ci build

### PR DESCRIPTION
**Pull request by MateusAndrade**
# Summary
This PR fix the CI when running the Build Sample App job on CircleCI adding a `clean`on Android.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |   ❌     |
| Android |    ❌     |

## Checklist

- [] I have tested this on a device and a simulator
- [] I added the documentation in `README.md`
- [] I mentioned this change in `CHANGELOG.md`
- [] I updated the typed files (TS and Flow)
- [] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by MateusAndrade** [comment]
> why?

Currently the CI is broken when running a ```./gradlew && ./gradlew build```.

Check: https://circleci.com/gh/react-native-community/react-native-camera/1193#tests/containers/0

**Comment by MateusAndrade** [comment]
Should merge?

**Comment by sibelius** [comment]
Yep

**Pull request merged**
