### PR TITLE
fix: only call requestRecordPermission in debug mode

### PR DESCRIPTION
**Pull request by n1ru4l**
@adimshev Could you please test if this resolves the issue you are experiencing in #2085?

```bash
# yarn
yarn add react-native-camera@git+https://git@github.com/react-native-community/react-native-camera.git#fix-2085
# npm
npm install --save react-native-camera@git+https://git@github.com/react-native-community/react-native-camera.git#fix-2085
```

### CODE REVIEW

**Comment by bonkowski** [comment]
I just verified that the fix works. My app was removed from TestFlight because we did not explain why we needed the microphone, which we didn't. After using this fix, it was accepted.

**Comment by idrisssakhi** [comment]
tested for me i use the qrcode scanner and this solved my issue

**Comment by ldgarcia** [comment]
The fix works for me too. Thanks!

**Comment by sipotat** [comment]
Also for me. Thank!

**Pull request merged**
