### PR TITLE
stop/release camera in non-UI thread

### PR DESCRIPTION
**Pull request by cristianoccazinsp**
# Summary

**Note: Changes still under testing. Do not merge yet until I fully confirm this causes no further issues in production. Will report back with findings in a week or so after I get enough testing. **

Update stop and surface destroyed code on Android (and Camera1) so the camera is released in a background thread (similar to the start updates).  This is due to release and stop preview being quite slow on some devices and reporting ANRs from time to time.

An example ANR that was recently reported:
```
ANR  Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 46.  Wait queue head age: 5506.2ms.) 
    Camera.java:-2 android.hardware.Camera.native_release
    Camera.java:673 android.hardware.Camera.release
    Camera1.java:1009 com.google.android.cameraview.Camera1.releaseCamera
    Camera1.java:242 com.google.android.cameraview.Camera1.stop
    Camera1.java:141 com.google.android.cameraview.Camera1$1.onSurfaceDestroyed
    PreviewImpl.java:60 com.google.android.cameraview.PreviewImpl.dispatchSurfaceDestroyed
    TextureViewPreview.java:59 com.google.android.cameraview.TextureViewPreview$1.onSurfaceTextureDestroyed
    TextureView.java:249 android.view.TextureView.releaseSurfaceTexture
    TextureView.java:222 android.view.TextureView.onDetachedFromWindowInternal
    View.java:18447 android.view.View.dispatchDetachedFromWindow
    ViewGroup.java:3771 android.view.ViewGroup.dispatchDetachedFromWindow
    ViewGroup.java:3771 android.view.ViewGroup.dispatchDetachedFromWindow
    ViewGroup.java:3771 android.view.ViewGroup.dispatchDetachedFromWindow
    ViewGroup.java:3771 android.view.ViewGroup.dispatchDetachedFromWindow
    ViewGroup.java:3771 android.view.ViewGroup.dispatchDetachedFromWindow
    ViewGroup.java:3771 android.view.ViewGroup.dispatchDetachedFromWindow
    ViewGroup.java:3771 android.view.ViewGroup.dispatchDetachedFromWindow
    ViewGroup.java:5362 android.view.ViewGroup.removeViewInternal
    ViewGroup.java:5309 android.view.ViewGroup.removeViewAt
    ReactViewGroup.java:469 com.facebook.react.views.view.ReactViewGroup.removeViewAt
    ReactViewManager.java:389 com.facebook.react.views.view.ReactViewManager.removeViewAt
    ReactViewManager.java:37 com.facebook.react.views.view.ReactViewManager.removeViewAt
    NativeViewHierarchyManager.java:457 com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren
    UIViewOperationQueue.java:205 com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute
    UIViewOperationQueue.java:779 com.facebook.react.uimanager.UIViewOperationQueue$1.run
    UIViewOperationQueue.java:888 com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches
    UIViewOperationQueue.java:42 com.facebook.react.uimanager.UIViewOperationQueue.access$2200
    UIViewOperationQueue.java:948 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded
    GuardedFrameCallback.java:28 com.facebook.react.uimanager.GuardedFrameCallback.doFrame
    ReactChoreographer.java:174 com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame
    ChoreographerCompat.java:84 com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame
    Choreographer.java:947 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:761 android.view.Choreographer.doCallbacks
    Choreographer.java:693 android.view.Choreographer.doFrame
    Choreographer.java:935 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:873 android.os.Handler.handleCallback
    Handler.java:99 android.os.Handler.dispatchMessage
    Looper.java:215 android.os.Looper.loop
    ActivityThread.java:6952 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:493 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:870 com.android.internal.os.ZygoteInit.main
```

## Test Plan

Initially tested on a Google Pixel 2 (Android 10) and motorola G5 (Android 8.1). Will be testing in production with multiple devices to confirm this change does not cause other issues and does indeed resolve the reported ANR.

### What's required for testing (prerequisites)?
Real device with camera

### What are the steps to reproduce (after prerequisites)?
Mount and dismount a <RNCamera> component. Observe how the application becomes non responsive on unmount for a brief period. After the update, unmounting should no longer block the UI and JS threads.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [X] I added the documentation in `README.md`
- [X] I mentioned this change in `CHANGELOG.md`
- [X] I updated the typed files (TS and Flow)
- [X] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by sibelius** [comment]
is this good to merge?

**Comment by cristianoccazinsp** [comment]
I've had it on beta for a week now, but still waiting for an actual prod
release. Can we wait a few more days? Still waiting for some more devices
to test it since it's a very device specific issue.

**Comment by cristianoccazinsp** [comment]
Added an extra change to resolve https://github.com/react-native-community/react-native-camera/issues/2698

Although the issue is not related to this change, the changes are strictly related. Still waiting to get more testing, but anyone is welcome to test it :)

**Comment by cristianoccazinsp** [comment]
Been testing on prod already; about 300 android users and no crashes or issues so far. @sibelius I think this is good to merge now. 

https://github.com/react-native-community/react-native-camera/issues/2698 can also be closed with this.

**Pull request merged**
