### PR TITLE
[iOS] Make GoogleMobileVision framework optional

### PR DESCRIPTION
**Pull request by brunolemos**
Make it optional for real. 
Having to add a postinstall script was not the ideal DX.

_PS1: It would be nice to make it really optional on Android too, removing the need of installing `play-services-vision`._

_PS2: Please test it on a project with face detection before deploying. I only tested on a project without face detection._

### CODE REVIEW

**Comment by jgfidelis** [comment]
I will take a look into this during the week, thanks, this could be really useful

**Comment by jgfidelis** [comment]
@brunolemos can you resolve the conflicts please?

**Comment by brunolemos** [comment]
@jgfidelis resolved

**Comment by jgfidelis** [comment]
@brunolemos , can you test if it works on https://github.com/react-native-community/rncamera-example? That is the rncamera demo app and it uses face detection. If it works there, then we can safely merge it :)

**Pull request merged**
