### PR TITLE
Bug/save to capture when app goes on pause

### PR DESCRIPTION
**Pull request by 6pm**

### CODE REVIEW

**Comment by 6pm** [comment]
Please rerun tests on circleci. Something wrong with internet connection.

**Comment by sibelius** [comment]
can you rebase and explain why this is needed?

**Comment by 6pm** [comment]
@sibelius how to reproduce on android device: take picture and immediately press 'home' button. After that go to app and try to take photo again - camera will be not works. 
It is edge case but I think that must be fixed.

**Comment by sibelius** [comment]
tks, it makes sense

**Pull request merged**
