### PR TITLE
Fine-grained podspec (iOS)

### PR DESCRIPTION
**Pull request by ognen**
Due to the rather involved installation setup for the use of the face detector on iOS with cocoapods, it is perhaps better that it is turned off by default when using the library via cocoapods.

Users wanting to use the face detector, can opt-in to do so.

To achieve this, this PR introduces subspecs for the 3 major components within the library:
- RN
- RCT
- FaceDetector

When using just 

```
pod 'react-native-camera' path: ...
```

Only RN and RCT are included by default. 

To also include the FaceDetector code, one should use

```
pod 'react-native-camera', subspecs: ['RCT', 'RN', 'FaceDetector'], path: '../node_modules/react-native-camera'
```

Ideally, one should also use the [pod for google vision](https://cocoapods.org/?q=google%20vision) when using cocoapods, but I leave that to someone that needs the feature to improve it ;).

### CODE REVIEW

**Comment by sibelius** [comment]
`patch-package` could solve for non cocoapods users?

**Comment by n1ru4l** [comment]
@sibelius I mean that I am using patch-package to fix the current podspec file and would love to have this change in the next release, so I do not need to patch it.

**Comment by sibelius** [comment]
@ognen tks for this

how can we improve the workflow for non cocoapods users?

**Comment by n1ru4l** [comment]
I think not using cocoapod is a mess and I am so happy that I ported our project to cocoapods for managing everything.

But maybe we could add a script that can be added as `prepare` which downloads the libraries?

 E.g. if there is a script that downloads boost https://github.com/react-native-community/boost-for-react-native you install react via cocoapods

**Comment by ognen** [comment]
@sibelius You would have to make the Google vision sources available and ready to be compiled within the Xcode project (so that `react-native link` just works). This could either be done via:
- an npm `prepare` script that does the downloading, unpacking and patching for you (as @n1ru4l suggest).
- git submodules

**Pull request merged**
