### PR TITLE
Remove recursive header search paths

### LINKED ISSUE #1407: Argument list too long: recursive header expansion failed
### Which implementation are you using
I'm using RNCamera

### Steps to reproduce
1. following documentation ( npm install react-native-camera --save)
2. react-native link
3. Manual link...

### Expected behaviour
I get a build fail and see the following

Argument list too long: recursive header expansion failed at /Users/*USER*/*APP*/node_modules/react-native-camera/ios/../../../ios/build/Index/DataStore/v5/records/1G.

### Actual behaviour
***FAILED BUILD***

### Environment
- **Node.js version**: LATEST
- **React Native version**: LATEST
- **React Native platform + platform version**: iOS 9.0

### react-native-camera
**Version**:  "master"

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

### PR DESCRIPTION
**Pull request by JChanceHud**
Removes the recursive header search paths for parent directories.

Closes #1407

### CODE REVIEW

**Comment by jgfidelis** [comment]
My app wont compile with this config.

**Comment by JChanceHud** [comment]
Hi @jgfidelis thanks for taking a look.

Could you supply some more info about the build error?

**Comment by jgfidelis** [comment]
It just doesn't find the FaceDetection frameworks and doesn't link them. Are you using face detection?

**Comment by JChanceHud** [comment]
No, that explains it though, I'll test it with face detection and see if I can reproduce/find a workaround.

**Pull request closed without merging**
